-- Delete existing NOAA tools before inserting
DELETE FROM "AvailableTools" WHERE workflow_name = 'NOAA';

-- Insert NOAA tool definitions
INSERT INTO "AvailableTools" (tool_name, workflow_name, description, required_parameters, optional_parameters, return_format) VALUES
('Get Datasets', 'NOAA', 'Browse available NOAA datasets',
    '{}',
    '{"datatypeid": "Filter by specific data type (e.g., TMAX,TMIN or PRCP)", 
      "locationid": "Filter by location (e.g., FIPS:37 for North Carolina)", 
      "stationid": "Filter by specific station",
      "startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "sortfield": "Sort by id, name, mindate, maxdate, or datacoverage",
      "sortorder": "asc or desc (defaults to asc)",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"id": "Dataset ID", "name": "Dataset name", "datacoverage": "Data coverage percentage", "mindate": "Earliest date", "maxdate": "Latest date", "description": "Dataset description"}'
),
('Get Data Categories', 'NOAA', 'Browse available NOAA data categories (e.g., temperature, precipitation)',
    '{}',
    '{"datasetid": "Filter by specific dataset",
      "locationid": "Filter by location",
      "stationid": "Filter by specific station",
      "startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "sortfield": "Sort by id, name",
      "sortorder": "asc or desc (defaults to asc)",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"id": "Category ID", "name": "Category name", "description": "Category description"}'
),
('Get Data Types', 'NOAA', 'Get detailed information about types of measurements available in NOAA datasets',
    '{}',
    '{"datasetid": "Filter by specific dataset",
      "locationid": "Filter by location",
      "stationid": "Filter by specific station",
      "datacategoryid": "Filter by data category (e.g., TEMP for temperature)",
      "startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "sortfield": "Sort by id, name, mindate, maxdate",
      "sortorder": "asc or desc (defaults to asc)",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"id": "Data type ID", "name": "Data type name", "description": "Data type description", "parameters": "Measurement parameters", "units": "Units of measurement"}'
),
('Get Location Categories', 'NOAA', 'Find available types of locations in NOAA datasets',
    '{}',
    '{"datasetid": "Filter by specific dataset",
      "startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "sortfield": "Sort by id, name",
      "sortorder": "asc or desc (defaults to asc)",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"id": "Location category ID", "name": "Location category name", "description": "Location category description"}'
),
('Get Locations', 'NOAA', 'Search for specific locations and their details in NOAA datasets',
    '{}',
    '{"datasetid": "Filter by specific dataset",
      "locationcategoryid": "Filter by location type (e.g., CITY, CNTY, STATE)",
      "datacategoryid": "Filter by data category (e.g., TEMP for temperature)",
      "startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "sortfield": "Sort by id, name, mindate, maxdate",
      "sortorder": "asc or desc (defaults to asc)",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"id": "Location ID", "name": "Location name", "type": "Location type", "geolocation": "Geographic details", "datacoverage": "Data coverage information"}'
),
('Get Stations', 'NOAA', 'Find weather/climate monitoring stations in NOAA datasets',
    '{}',
    '{"datasetid": "Filter by specific dataset",
      "locationid": "Filter by location",
      "datacategoryid": "Filter by data category (e.g., TEMP for temperature)",
      "datatypeid": "Filter by specific data type",
      "extent": "Search within a geographic extent",
      "startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "sortfield": "Sort by id, name, mindate, maxdate, datacoverage",
      "sortorder": "asc or desc (defaults to asc)",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"id": "Station ID", "name": "Station name", "location": "Location details", "elevation": "Elevation", "datacoverage": "Data coverage", "datatypes": "Available data types"}'
),
('Get Data', 'NOAA', 'Get actual weather and climate measurements from NOAA datasets',
    '{"datasetid": "The dataset to fetch data from (e.g., GHCND)", 
      "startdate": "Start date in ISO format (YYYY-MM-DD)", 
      "enddate": "End date in ISO format (YYYY-MM-DD)"}',
    '{"datatypeid": "Type of data to retrieve (e.g., TMAX for max temperature)",
      "locationid": "Specific location to get data for",
      "stationid": "Specific station to get data from",
      "units": "standard or metric (defaults to standard)",
      "includemetadata": "Include metadata in the response",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"station": "Station information", "datatype": "Data type details", "date": "Date of measurement", "value": "Actual measurement value", "attributes": "Data attributes", "flags": "Quality flags"}'
),
('Get Metrics', 'NOAA', 'Get statistical metrics for NOAA data points',
    '{"datasetid": "The dataset to fetch metrics from", 
      "startdate": "Start date in ISO format (YYYY-MM-DD)", 
      "enddate": "End date in ISO format (YYYY-MM-DD)"}',
    '{"locationid": "Filter by specific location",
      "stationid": "Filter by specific station",
      "datatypeid": "Filter by specific data type",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"metrics": "Statistical metrics", "aggregates": "Aggregated values", "quality": "Data quality indicators", "coverage": "Coverage statistics"}'
),
('Get Normals', 'NOAA', 'Access climatological normals data from NOAA datasets',
    '{"datasetid": "The dataset to fetch normals from (e.g., NORMAL_DLY)", 
      "startdate": "Start date in ISO format (YYYY-MM-DD)", 
      "enddate": "End date in ISO format (YYYY-MM-DD)"}',
    '{"locationid": "Filter by specific location",
      "stationid": "Filter by specific station",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"station": "Station information", "normals": "Normal values", "period": "Period of record", "confidence": "Statistical confidence intervals"}'
),
('Get Summaries', 'NOAA', 'Get period summaries from NOAA datasets',
    '{"datasetid": "The dataset to fetch summaries from", 
      "startdate": "Start date in ISO format (YYYY-MM-DD)", 
      "enddate": "End date in ISO format (YYYY-MM-DD)"}',
    '{"locationid": "Filter by specific location",
      "stationid": "Filter by specific station",
      "datatypeid": "Filter by specific data type",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"summary": "Period summary statistics", "aggregates": "Aggregated values", "completeness": "Data completeness info", "quality": "Quality indicators"}'
),
('Get Quality', 'NOAA', 'Access quality control information for NOAA data',
    '{"datasetid": "The dataset to check quality for", 
      "startdate": "Start date in ISO format (YYYY-MM-DD)", 
      "enddate": "End date in ISO format (YYYY-MM-DD)"}',
    '{"locationid": "Filter by specific location",
      "stationid": "Filter by specific station",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"flags": "Quality control flags", "validation": "Data validation results", "qa_metrics": "Quality assurance metrics", "reliability": "Data reliability indicators"}'
),
('Get Coverage', 'NOAA', 'Check data availability and coverage in NOAA datasets',
    '{"datasetid": "The dataset to check coverage for"}',
    '{"startdate": "Start date in ISO format (YYYY-MM-DD)",
      "enddate": "End date in ISO format (YYYY-MM-DD)",
      "locationid": "Filter by specific location",
      "stationid": "Filter by specific station",
      "limit": "Maximum records to return (max 1000, default 25)",
      "offset": "Records to skip for pagination"}',
    '{"coverage": "Data coverage percentages", "temporal": "Temporal coverage info", "spatial": "Spatial coverage details", "completeness": "Data completeness metrics"}');